"""esquema inicial

Revision ID: d3a8fff07aa6
Revises: 
Create Date: 2026-09-25 13:04:34.721073
"""
from alembic import op
import sqlalchemy as sa


revision = 'd3a8fff07aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regra',
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('vistoria_id', sa.String(length=32), nullable=True),
    sa.Column('adotada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texto')
    )
    op.create_table('usuario',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('vistoria',
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('endereco', sa.String(length=400), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('data_vistoria', sa.String(length=20), nullable=False),
    sa.Column('arquivada', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comodo',
    sa.Column('vistoria_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('erro', sa.Text(), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fotos_utilizaveis', sa.Integer(), nullable=False),
    sa.Column('cobertura_incompleta', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vistoria_id'], ['vistoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vistoria_id', 'nome', name='uq_comodo_nome')
    )
    with op.batch_alter_table('comodo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comodo_vistoria_id'), ['vistoria_id'], unique=False)

    op.create_table('correcao_humana',
    sa.Column('vistoria_id', sa.String(length=32), nullable=False),
    sa.Column('pendencia_id', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('razao', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vistoria_id'], ['vistoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correcao_humana', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correcao_humana_vistoria_id'), ['vistoria_id'], unique=False)

    op.create_table('job',
    sa.Column('vistoria_id', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('concluidos', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=False),
    sa.Column('comodos', sa.Text(), nullable=False),
    sa.Column('usar_evidencias', sa.Boolean(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelamento_pedido', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vistoria_id'], ['vistoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_vistoria_id'), ['vistoria_id'], unique=False)

    op.create_table('sessao',
    sa.Column('usuario_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('foto',
    sa.Column('comodo_id', sa.String(length=32), nullable=False),
    sa.Column('nome_original', sa.String(length=300), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('bytes_tamanho', sa.Integer(), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=20), nullable=False),
    sa.Column('relevancia', sa.Integer(), nullable=False),
    sa.Column('ambiente_adjacente', sa.Boolean(), nullable=False),
    sa.Column('reflexo', sa.Boolean(), nullable=False),
    sa.Column('motivo_escopo', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comodo_id'], ['comodo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_comodo_id'), ['comodo_id'], unique=False)

    op.create_table('item_laudo',
    sa.Column('comodo_id', sa.String(length=32), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('certeza', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('removido', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comodo_id'], ['comodo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_laudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_laudo_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_laudo_comodo_id'), ['comodo_id'], unique=False)

    op.create_table('evidencia',
    sa.Column('comodo_id', sa.String(length=32), nullable=False),
    sa.Column('foto_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.Column('confianca_percepcao', sa.Integer(), nullable=False),
    sa.Column('confianca_escopo', sa.Integer(), nullable=False),
    sa.Column('confianca_final', sa.Integer(), nullable=False),
    sa.Column('e_reflexo', sa.Boolean(), nullable=False),
    sa.Column('e_ambiente_adjacente', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo_descarte', sa.String(length=40), nullable=False),
    sa.Column('detalhe_descarte', sa.Text(), nullable=False),
    sa.Column('regiao_x', sa.Float(), nullable=True),
    sa.Column('regiao_y', sa.Float(), nullable=True),
    sa.Column('regiao_largura', sa.Float(), nullable=True),
    sa.Column('regiao_altura', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comodo_id'], ['comodo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item_laudo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidencia_comodo_id'), ['comodo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencia_foto_id'), ['foto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencia_item_id'), ['item_id'], unique=False)

    op.create_table('historico_item',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('texto_anterior', sa.Text(), nullable=False),
    sa.Column('texto_novo', sa.Text(), nullable=False),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('pendencia_id', sa.String(length=32), nullable=True),
    sa.Column('usuario_id', sa.String(length=32), nullable=True),
    sa.Column('evidencia_ids', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_laudo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_item_item_id'), ['item_id'], unique=False)

    op.create_table('pendencia',
    sa.Column('comodo_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('certeza', sa.Integer(), nullable=False),
    sa.Column('texto_proposto', sa.Text(), nullable=False),
    sa.Column('decisao', sa.String(length=20), nullable=False),
    sa.Column('correcao', sa.Text(), nullable=False),
    sa.Column('regra_sugerida', sa.Text(), nullable=False),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvida_por_id', sa.String(length=32), nullable=True),
    sa.Column('evidencia_ids', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comodo_id'], ['comodo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item_laudo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolvida_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pendencia_comodo_id'), ['comodo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pendencia_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pendencia_item_id'))
        batch_op.drop_index(batch_op.f('ix_pendencia_comodo_id'))

    op.drop_table('pendencia')
    with op.batch_alter_table('historico_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_item_item_id'))

    op.drop_table('historico_item')
    with op.batch_alter_table('evidencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidencia_item_id'))
        batch_op.drop_index(batch_op.f('ix_evidencia_foto_id'))
        batch_op.drop_index(batch_op.f('ix_evidencia_comodo_id'))

    op.drop_table('evidencia')
    with op.batch_alter_table('item_laudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_laudo_comodo_id'))
        batch_op.drop_index(batch_op.f('ix_item_laudo_categoria'))

    op.drop_table('item_laudo')
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_comodo_id'))

    op.drop_table('foto')
    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sessao_token_hash'))

    op.drop_table('sessao')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_vistoria_id'))

    op.drop_table('job')
    with op.batch_alter_table('correcao_humana', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correcao_humana_vistoria_id'))

    op.drop_table('correcao_humana')
    with op.batch_alter_table('comodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comodo_vistoria_id'))

    op.drop_table('comodo')
    op.drop_table('vistoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('regra')
    # ### end Alembic commands ###
